# Serverless Application by Olatunji Olayinka Oluwaseun

service: basic-serverless-lambda

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: src/handler.generateRandomNumber
